{{- if .Values.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: {{ required "If enabling the HorizontalPodAutoscaler, you must provide .Values.horizontalPodAutoscaler.minReplicas!" .Values.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ required "If enabling the HorizontalPodAutoscaler, you must provide .Values.horizontalPodAutoscaler.maxReplicas!" .Values.horizontalPodAutoscaler.maxReplicas }}
  metrics:
    {{- with .Values.horizontalPodAutoscaler }}
    {{- if eq (required "If enabling the HorizontalPodAutoscaler, you must provide .type!" .type) "cpu" "memory" }}
    - type: Resource
      resource:
        name: {{ required "If enabling the HorizontalPodAutoscaler, you must provide .type!" .type }}
        targetAverageUtilization: {{ required "If enabling the HorizontalPodAutoscaler, you must provide .utilizationPercentage!" .utilizationPercentage }}
    {{- else if eq .type "custom" }}
    - type: External
      external:
        metric:
          name: {{ .customMetric.name }}
          selector:
            matchLabels:
            {{- with .customMetric.filter }}
{{- toYaml . | nindent 14 }}
            {{- end }}
        target:
          type: AverageValue
          averageValue: {{ required "If enabling the HorizontalPodAutoscaler, you must provide .utilizationPercentage!" .utilizationPercentage }}
    {{- end }}
    {{- end }}
{{- end }}
